#pragma once
#include <FS.h>
#include <LocatorAPI.h>
#include <format>
#include <gli/gli.hpp>
#include <ktx.h>
#include <ktxvulkan.h>
#include <map>
#include <memory>
#include <optional>

namespace rv::texture {

static const std::map<gli::format, VkFormat> gliToVkFormatMap = {
    // Packed 4/5/6-bit formats
    {gli::FORMAT_RG4_UNORM_PACK8, VK_FORMAT_R4G4_UNORM_PACK8},
    {gli::FORMAT_RGBA4_UNORM_PACK16, VK_FORMAT_R4G4B4A4_UNORM_PACK16},
    {gli::FORMAT_BGRA4_UNORM_PACK16, VK_FORMAT_B4G4R4A4_UNORM_PACK16},
    {gli::FORMAT_R5G6B5_UNORM_PACK16, VK_FORMAT_R5G6B5_UNORM_PACK16},
    {gli::FORMAT_B5G6R5_UNORM_PACK16, VK_FORMAT_B5G6R5_UNORM_PACK16},
    {gli::FORMAT_RGB5A1_UNORM_PACK16, VK_FORMAT_R5G5B5A1_UNORM_PACK16},
    {gli::FORMAT_BGR5A1_UNORM_PACK16, VK_FORMAT_B5G5R5A1_UNORM_PACK16},
    {gli::FORMAT_A1RGB5_UNORM_PACK16, VK_FORMAT_A1R5G5B5_UNORM_PACK16},

    // R8
    {gli::FORMAT_R8_UNORM_PACK8, VK_FORMAT_R8_UNORM},
    {gli::FORMAT_R8_SNORM_PACK8, VK_FORMAT_R8_SNORM},
    {gli::FORMAT_R8_USCALED_PACK8, VK_FORMAT_R8_USCALED},
    {gli::FORMAT_R8_SSCALED_PACK8, VK_FORMAT_R8_SSCALED},
    {gli::FORMAT_R8_UINT_PACK8, VK_FORMAT_R8_UINT},
    {gli::FORMAT_R8_SINT_PACK8, VK_FORMAT_R8_SINT},
    {gli::FORMAT_R8_SRGB_PACK8, VK_FORMAT_R8_SRGB},

    // RG8
    {gli::FORMAT_RG8_UNORM_PACK8, VK_FORMAT_R8G8_UNORM},
    {gli::FORMAT_RG8_SNORM_PACK8, VK_FORMAT_R8G8_SNORM},
    {gli::FORMAT_RG8_USCALED_PACK8, VK_FORMAT_R8G8_USCALED},
    {gli::FORMAT_RG8_SSCALED_PACK8, VK_FORMAT_R8G8_SSCALED},
    {gli::FORMAT_RG8_UINT_PACK8, VK_FORMAT_R8G8_UINT},
    {gli::FORMAT_RG8_SINT_PACK8, VK_FORMAT_R8G8_SINT},
    {gli::FORMAT_RG8_SRGB_PACK8, VK_FORMAT_R8G8_SRGB},

    // RGB8
    {gli::FORMAT_RGB8_UNORM_PACK8, VK_FORMAT_R8G8B8_UNORM},
    {gli::FORMAT_RGB8_SNORM_PACK8, VK_FORMAT_R8G8B8_SNORM},
    {gli::FORMAT_RGB8_USCALED_PACK8, VK_FORMAT_R8G8B8_USCALED},
    {gli::FORMAT_RGB8_SSCALED_PACK8, VK_FORMAT_R8G8B8_SSCALED},
    {gli::FORMAT_RGB8_UINT_PACK8, VK_FORMAT_R8G8B8_UINT},
    {gli::FORMAT_RGB8_SINT_PACK8, VK_FORMAT_R8G8B8_SINT},
    {gli::FORMAT_RGB8_SRGB_PACK8, VK_FORMAT_R8G8B8_SRGB},

    // BGR8
    {gli::FORMAT_BGR8_UNORM_PACK8, VK_FORMAT_B8G8R8_UNORM},
    {gli::FORMAT_BGR8_SNORM_PACK8, VK_FORMAT_B8G8R8_SNORM},
    {gli::FORMAT_BGR8_USCALED_PACK8, VK_FORMAT_B8G8R8_USCALED},
    {gli::FORMAT_BGR8_SSCALED_PACK8, VK_FORMAT_B8G8R8_SSCALED},
    {gli::FORMAT_BGR8_UINT_PACK8, VK_FORMAT_B8G8R8_UINT},
    {gli::FORMAT_BGR8_SINT_PACK8, VK_FORMAT_B8G8R8_SINT},
    {gli::FORMAT_BGR8_SRGB_PACK8, VK_FORMAT_B8G8R8_SRGB},

    // RGBA8
    {gli::FORMAT_RGBA8_UNORM_PACK8, VK_FORMAT_R8G8B8A8_UNORM},
    {gli::FORMAT_RGBA8_SNORM_PACK8, VK_FORMAT_R8G8B8A8_SNORM},
    {gli::FORMAT_RGBA8_USCALED_PACK8, VK_FORMAT_R8G8B8A8_USCALED},
    {gli::FORMAT_RGBA8_SSCALED_PACK8, VK_FORMAT_R8G8B8A8_SSCALED},
    {gli::FORMAT_RGBA8_UINT_PACK8, VK_FORMAT_R8G8B8A8_UINT},
    {gli::FORMAT_RGBA8_SINT_PACK8, VK_FORMAT_R8G8B8A8_SINT},
    {gli::FORMAT_RGBA8_SRGB_PACK8, VK_FORMAT_R8G8B8A8_SRGB},

    // BGRA8
    {gli::FORMAT_BGRA8_UNORM_PACK8, VK_FORMAT_B8G8R8A8_UNORM},
    {gli::FORMAT_BGRA8_SNORM_PACK8, VK_FORMAT_B8G8R8A8_SNORM},
    {gli::FORMAT_BGRA8_USCALED_PACK8, VK_FORMAT_B8G8R8A8_USCALED},
    {gli::FORMAT_BGRA8_SSCALED_PACK8, VK_FORMAT_B8G8R8A8_SSCALED},
    {gli::FORMAT_BGRA8_UINT_PACK8, VK_FORMAT_B8G8R8A8_UINT},
    {gli::FORMAT_BGRA8_SINT_PACK8, VK_FORMAT_B8G8R8A8_SINT},
    {gli::FORMAT_BGRA8_SRGB_PACK8, VK_FORMAT_B8G8R8A8_SRGB},

    // 32-bit packed RGBA
    {gli::FORMAT_RGBA8_UNORM_PACK32, VK_FORMAT_R8G8B8A8_UNORM},
    {gli::FORMAT_RGBA8_SNORM_PACK32, VK_FORMAT_R8G8B8A8_SNORM},
    {gli::FORMAT_RGBA8_USCALED_PACK32, VK_FORMAT_R8G8B8A8_USCALED},
    {gli::FORMAT_RGBA8_SSCALED_PACK32, VK_FORMAT_R8G8B8A8_SSCALED},
    {gli::FORMAT_RGBA8_UINT_PACK32, VK_FORMAT_R8G8B8A8_UINT},
    {gli::FORMAT_RGBA8_SINT_PACK32, VK_FORMAT_R8G8B8A8_SINT},
    {gli::FORMAT_RGBA8_SRGB_PACK32, VK_FORMAT_R8G8B8A8_SRGB},

    // RGB10A2
    {gli::FORMAT_RGB10A2_UNORM_PACK32, VK_FORMAT_A2B10G10R10_UNORM_PACK32},
    {gli::FORMAT_RGB10A2_UINT_PACK32, VK_FORMAT_A2B10G10R10_UINT_PACK32},
    {gli::FORMAT_BGR10A2_UNORM_PACK32, VK_FORMAT_A2R10G10B10_UNORM_PACK32},
    {gli::FORMAT_BGR10A2_UINT_PACK32, VK_FORMAT_A2R10G10B10_UINT_PACK32},

    // R16
    {gli::FORMAT_R16_UNORM_PACK16, VK_FORMAT_R16_UNORM},
    {gli::FORMAT_R16_SNORM_PACK16, VK_FORMAT_R16_SNORM},
    {gli::FORMAT_R16_USCALED_PACK16, VK_FORMAT_R16_USCALED},
    {gli::FORMAT_R16_SSCALED_PACK16, VK_FORMAT_R16_SSCALED},
    {gli::FORMAT_R16_UINT_PACK16, VK_FORMAT_R16_UINT},
    {gli::FORMAT_R16_SINT_PACK16, VK_FORMAT_R16_SINT},
    {gli::FORMAT_R16_SFLOAT_PACK16, VK_FORMAT_R16_SFLOAT},

    // RG16
    {gli::FORMAT_RG16_UNORM_PACK16, VK_FORMAT_R16G16_UNORM},
    {gli::FORMAT_RG16_SNORM_PACK16, VK_FORMAT_R16G16_SNORM},
    {gli::FORMAT_RG16_USCALED_PACK16, VK_FORMAT_R16G16_USCALED},
    {gli::FORMAT_RG16_SSCALED_PACK16, VK_FORMAT_R16G16_SSCALED},
    {gli::FORMAT_RG16_UINT_PACK16, VK_FORMAT_R16G16_UINT},
    {gli::FORMAT_RG16_SINT_PACK16, VK_FORMAT_R16G16_SINT},
    {gli::FORMAT_RG16_SFLOAT_PACK16, VK_FORMAT_R16G16_SFLOAT},

    // RGB16
    {gli::FORMAT_RGB16_UNORM_PACK16, VK_FORMAT_R16G16B16_UNORM},
    {gli::FORMAT_RGB16_SNORM_PACK16, VK_FORMAT_R16G16B16_SNORM},
    {gli::FORMAT_RGB16_USCALED_PACK16, VK_FORMAT_R16G16B16_USCALED},
    {gli::FORMAT_RGB16_SSCALED_PACK16, VK_FORMAT_R16G16B16_SSCALED},
    {gli::FORMAT_RGB16_UINT_PACK16, VK_FORMAT_R16G16B16_UINT},
    {gli::FORMAT_RGB16_SINT_PACK16, VK_FORMAT_R16G16B16_SINT},
    {gli::FORMAT_RGB16_SFLOAT_PACK16, VK_FORMAT_R16G16B16_SFLOAT},

    // RGBA16
    {gli::FORMAT_RGBA16_UNORM_PACK16, VK_FORMAT_R16G16B16A16_UNORM},
    {gli::FORMAT_RGBA16_SNORM_PACK16, VK_FORMAT_R16G16B16A16_SNORM},
    {gli::FORMAT_RGBA16_USCALED_PACK16, VK_FORMAT_R16G16B16A16_USCALED},
    {gli::FORMAT_RGBA16_SSCALED_PACK16, VK_FORMAT_R16G16B16A16_SSCALED},
    {gli::FORMAT_RGBA16_UINT_PACK16, VK_FORMAT_R16G16B16A16_UINT},
    {gli::FORMAT_RGBA16_SINT_PACK16, VK_FORMAT_R16G16B16A16_SINT},
    {gli::FORMAT_RGBA16_SFLOAT_PACK16, VK_FORMAT_R16G16B16A16_SFLOAT},

    // R32
    {gli::FORMAT_R32_UINT_PACK32, VK_FORMAT_R32_UINT},
    {gli::FORMAT_R32_SINT_PACK32, VK_FORMAT_R32_SINT},
    {gli::FORMAT_R32_SFLOAT_PACK32, VK_FORMAT_R32_SFLOAT},

    // RG32
    {gli::FORMAT_RG32_UINT_PACK32, VK_FORMAT_R32G32_UINT},
    {gli::FORMAT_RG32_SINT_PACK32, VK_FORMAT_R32G32_SINT},
    {gli::FORMAT_RG32_SFLOAT_PACK32, VK_FORMAT_R32G32_SFLOAT},

    // RGB32
    {gli::FORMAT_RGB32_UINT_PACK32, VK_FORMAT_R32G32B32_UINT},
    {gli::FORMAT_RGB32_SINT_PACK32, VK_FORMAT_R32G32B32_SINT},
    {gli::FORMAT_RGB32_SFLOAT_PACK32, VK_FORMAT_R32G32B32_SFLOAT},

    // RGBA32
    {gli::FORMAT_RGBA32_UINT_PACK32, VK_FORMAT_R32G32B32A32_UINT},
    {gli::FORMAT_RGBA32_SINT_PACK32, VK_FORMAT_R32G32B32A32_SINT},
    {gli::FORMAT_RGBA32_SFLOAT_PACK32, VK_FORMAT_R32G32B32A32_SFLOAT},

    // R64
    {gli::FORMAT_R64_UINT_PACK64, VK_FORMAT_R64_UINT},
    {gli::FORMAT_R64_SINT_PACK64, VK_FORMAT_R64_SINT},
    {gli::FORMAT_R64_SFLOAT_PACK64, VK_FORMAT_R64_SFLOAT},

    // RG64
    {gli::FORMAT_RG64_UINT_PACK64, VK_FORMAT_R64G64_UINT},
    {gli::FORMAT_RG64_SINT_PACK64, VK_FORMAT_R64G64_SINT},
    {gli::FORMAT_RG64_SFLOAT_PACK64, VK_FORMAT_R64G64_SFLOAT},

    // RGB64
    {gli::FORMAT_RGB64_UINT_PACK64, VK_FORMAT_R64G64B64_UINT},
    {gli::FORMAT_RGB64_SINT_PACK64, VK_FORMAT_R64G64B64_SINT},
    {gli::FORMAT_RGB64_SFLOAT_PACK64, VK_FORMAT_R64G64B64_SFLOAT},

    // RGBA64
    {gli::FORMAT_RGBA64_UINT_PACK64, VK_FORMAT_R64G64B64A64_UINT},
    {gli::FORMAT_RGBA64_SINT_PACK64, VK_FORMAT_R64G64B64A64_SINT},
    {gli::FORMAT_RGBA64_SFLOAT_PACK64, VK_FORMAT_R64G64B64A64_SFLOAT},

    // Special packed floating-point formats
    {gli::FORMAT_RG11B10_UFLOAT_PACK32, VK_FORMAT_B10G11R11_UFLOAT_PACK32},
    {gli::FORMAT_RGB9E5_UFLOAT_PACK32, VK_FORMAT_E5B9G9R9_UFLOAT_PACK32},

    // Depth/stencil
    {gli::FORMAT_D16_UNORM_PACK16, VK_FORMAT_D16_UNORM},
    {gli::FORMAT_D24_UNORM_PACK32, VK_FORMAT_X8_D24_UNORM_PACK32},
    {gli::FORMAT_D32_SFLOAT_PACK32, VK_FORMAT_D32_SFLOAT},
    {gli::FORMAT_S8_UINT_PACK8, VK_FORMAT_S8_UINT},
    {gli::FORMAT_D16_UNORM_S8_UINT_PACK32, VK_FORMAT_D16_UNORM_S8_UINT},
    {gli::FORMAT_D24_UNORM_S8_UINT_PACK32, VK_FORMAT_D24_UNORM_S8_UINT},
    {gli::FORMAT_D32_SFLOAT_S8_UINT_PACK64, VK_FORMAT_D32_SFLOAT_S8_UINT},

    // BC / DXT
    {gli::FORMAT_RGB_DXT1_UNORM_BLOCK8, VK_FORMAT_BC1_RGB_UNORM_BLOCK},
    {gli::FORMAT_RGB_DXT1_SRGB_BLOCK8, VK_FORMAT_BC1_RGB_SRGB_BLOCK},
    {gli::FORMAT_RGBA_DXT1_UNORM_BLOCK8, VK_FORMAT_BC1_RGBA_UNORM_BLOCK},
    {gli::FORMAT_RGBA_DXT1_SRGB_BLOCK8, VK_FORMAT_BC1_RGBA_SRGB_BLOCK},
    {gli::FORMAT_RGBA_DXT3_UNORM_BLOCK16, VK_FORMAT_BC2_UNORM_BLOCK},
    {gli::FORMAT_RGBA_DXT3_SRGB_BLOCK16, VK_FORMAT_BC2_SRGB_BLOCK},
    {gli::FORMAT_RGBA_DXT5_UNORM_BLOCK16, VK_FORMAT_BC3_UNORM_BLOCK},
    {gli::FORMAT_RGBA_DXT5_SRGB_BLOCK16, VK_FORMAT_BC3_SRGB_BLOCK},

    // ATI / BC4 / BC5
    {gli::FORMAT_R_ATI1N_UNORM_BLOCK8, VK_FORMAT_BC4_UNORM_BLOCK},
    {gli::FORMAT_R_ATI1N_SNORM_BLOCK8, VK_FORMAT_BC4_SNORM_BLOCK},
    {gli::FORMAT_RG_ATI2N_UNORM_BLOCK16, VK_FORMAT_BC5_UNORM_BLOCK},
    {gli::FORMAT_RG_ATI2N_SNORM_BLOCK16, VK_FORMAT_BC5_SNORM_BLOCK},

    // BPTC
    {gli::FORMAT_RGB_BP_UFLOAT_BLOCK16, VK_FORMAT_BC6H_UFLOAT_BLOCK},
    {gli::FORMAT_RGB_BP_SFLOAT_BLOCK16, VK_FORMAT_BC6H_SFLOAT_BLOCK},
    {gli::FORMAT_RGBA_BP_UNORM_BLOCK16, VK_FORMAT_BC7_UNORM_BLOCK},
    {gli::FORMAT_RGBA_BP_SRGB_BLOCK16, VK_FORMAT_BC7_SRGB_BLOCK},

    // ETC2 / EAC
    {gli::FORMAT_RGB_ETC2_UNORM_BLOCK8, VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK},
    {gli::FORMAT_RGB_ETC2_SRGB_BLOCK8, VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ETC2_UNORM_BLOCK8, VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ETC2_SRGB_BLOCK8, VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ETC2_UNORM_BLOCK16, VK_FORMAT_EAC_R11G11_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ETC2_SRGB_BLOCK16, VK_FORMAT_EAC_R11G11_SNORM_BLOCK},
    {gli::FORMAT_R_EAC_UNORM_BLOCK8, VK_FORMAT_EAC_R11_UNORM_BLOCK},
    {gli::FORMAT_R_EAC_SNORM_BLOCK8, VK_FORMAT_EAC_R11_SNORM_BLOCK},
    {gli::FORMAT_RG_EAC_UNORM_BLOCK16, VK_FORMAT_EAC_R11G11_UNORM_BLOCK},
    {gli::FORMAT_RG_EAC_SNORM_BLOCK16, VK_FORMAT_EAC_R11G11_SNORM_BLOCK},

    // ASTC
    {gli::FORMAT_RGBA_ASTC_4X4_UNORM_BLOCK16, VK_FORMAT_ASTC_4x4_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_4X4_SRGB_BLOCK16, VK_FORMAT_ASTC_4x4_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_5X4_UNORM_BLOCK16, VK_FORMAT_ASTC_5x4_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_5X4_SRGB_BLOCK16, VK_FORMAT_ASTC_5x4_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_5X5_UNORM_BLOCK16, VK_FORMAT_ASTC_5x5_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_5X5_SRGB_BLOCK16, VK_FORMAT_ASTC_5x5_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_6X5_UNORM_BLOCK16, VK_FORMAT_ASTC_6x5_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_6X5_SRGB_BLOCK16, VK_FORMAT_ASTC_6x5_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_6X6_UNORM_BLOCK16, VK_FORMAT_ASTC_6x6_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_6X6_SRGB_BLOCK16, VK_FORMAT_ASTC_6x6_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X5_UNORM_BLOCK16, VK_FORMAT_ASTC_8x5_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X5_SRGB_BLOCK16, VK_FORMAT_ASTC_8x5_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X6_UNORM_BLOCK16, VK_FORMAT_ASTC_8x6_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X6_SRGB_BLOCK16, VK_FORMAT_ASTC_8x6_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X8_UNORM_BLOCK16, VK_FORMAT_ASTC_8x8_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_8X8_SRGB_BLOCK16, VK_FORMAT_ASTC_8x8_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X5_UNORM_BLOCK16, VK_FORMAT_ASTC_10x5_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X5_SRGB_BLOCK16, VK_FORMAT_ASTC_10x5_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X6_UNORM_BLOCK16, VK_FORMAT_ASTC_10x6_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X6_SRGB_BLOCK16, VK_FORMAT_ASTC_10x6_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X8_UNORM_BLOCK16, VK_FORMAT_ASTC_10x8_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X8_SRGB_BLOCK16, VK_FORMAT_ASTC_10x8_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X10_UNORM_BLOCK16,
     VK_FORMAT_ASTC_10x10_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_10X10_SRGB_BLOCK16, VK_FORMAT_ASTC_10x10_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_12X10_UNORM_BLOCK16,
     VK_FORMAT_ASTC_12x10_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_12X10_SRGB_BLOCK16, VK_FORMAT_ASTC_12x10_SRGB_BLOCK},
    {gli::FORMAT_RGBA_ASTC_12X12_UNORM_BLOCK16,
     VK_FORMAT_ASTC_12x12_UNORM_BLOCK},
    {gli::FORMAT_RGBA_ASTC_12X12_SRGB_BLOCK16, VK_FORMAT_ASTC_12x12_SRGB_BLOCK},

    // ETC1
    {gli::FORMAT_RGB_ETC_UNORM_BLOCK8, VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK},
};

inline auto gliToVkFormat(gli::format format) -> std::optional<VkFormat> {
  auto itt = gliToVkFormatMap.find(format);

  if (itt != gliToVkFormatMap.end())
    return itt->second;
  else
    return std::nullopt;
}

inline auto load_dds_image(std::fs::path file, bool VFS = true)
    -> std::optional<gli::texture> {
  PROF_EVENT_N("Loading DDS");
  ZoneText(file.c_str(), file.string().size());
  bool isValid = VFS ? (bool)FS.exist(file) : std::fs::exists(file);
  if (!isValid)
    std::nullopt;

  if (VFS) {
    auto *fs = FS.r_open(file.c_str());
    return gli::load_dds(static_cast<char *>(fs->pointer()), fs->length());
  }
  return gli::load_dds(file.c_str());
}

static inline void ktxTextureDeleter(ktxTexture2 *ktxTex) {
  if (ktxTex) {
    ktxTexture2_Destroy(ktxTex);
  }
}

using ktxTexsturePtr_t = std::shared_ptr<ktxTexture2>;

// TODO: teach FS how to rearn files from the drive the same way
// TODO: update to c++23 and use std::expected
inline auto
load_ktx2_image(std::fs::path file,
                ktx_transcode_fmt_e targetTranscodeFormat = KTX_TTF_BC7_RGBA)
    -> std::pair<std::optional<ktxTexsturePtr_t>, std::string> {
  PROF_EVENT_N("Loading KTX2");
  ZoneText(file.c_str(), file.string().size());
  if (!std::fs::exists(file)) {
    return {std::nullopt,
            std::format("KTX2 image not found: %s", file.c_str())};
  }

  ktxTexture2 *ktxTex = nullptr;
  if (auto result = ktxTexture2_CreateFromNamedFile(
          file.c_str(), KTX_TEXTURE_CREATE_LOAD_IMAGE_DATA_BIT, &ktxTex);
      result != KTX_SUCCESS) {
    return {std::nullopt,
            std::format("KTX2 image can't be load: %s. Error code: %d",
                        file.c_str(), static_cast<uint32_t>(result))};
  }

  if (ktxTexture2_NeedsTranscoding(ktxTex)) {
    auto result = ktxTexture2_TranscodeBasis(ktxTex, targetTranscodeFormat, 0);
    if (result != KTX_SUCCESS) {
      return {std::nullopt,
              std::format("KTX2 image can't be transcoded: %s. Error code: %d",
                          file.c_str(), static_cast<uint32_t>(result))};
    }
  }

  return {ktxTexsturePtr_t(ktxTex, ktxTextureDeleter), {}};
}

}; // namespace rv::texture