set(XRPLATFORM_UNIX_H xrPlatform_Unix.h)

# Windows-specific definitions
add_module(XRay.Platform.Unix
  INCLUDES
  ${CMAKE_CURRENT_SOURCE_DIR}

  DEFINES
  VC_EXTRALEAN
  _CRT_SECURE_NO_DEPRECATE

  NOGDICAPMASKS
  NOMENUS
  NOICONS
  NOKEYSTATES
  NODRAWTEXT
  NOMEMMGR
  NOMETAFILE
  NOSERVICE
  NOCOMM
  NOHELP
  NOPROFILER
  NOMCX
  NOMINMAX
  #_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING

  SOURCES
  ${XRPLATFORM_UNIX_H}
)

# FIXME: Suppress warnings
target_compile_options(XRay.Platform.Unix
  INTERFACE
  $<$<CXX_COMPILER_ID:Clang>:-include${XRPLATFORM_UNIX_H}>
  $<$<CXX_COMPILER_ID:GNU>:-include${XRPLATFORM_UNIX_H}>
)

target_link_libraries(XRay.Platform
  INTERFACE
  $<$<PLATFORM_ID:Unix>:XRay.Platform.Unix>
)