module;

#include "_vector2.h"
#include "_vector3d.h"
#include "_vector3d_ext.h"
#include "_vector4.h"
#include "_sphere.h"
#include "_rect.h"
#include "_random.h"
#include "_quaternion.h"
#include "_quaternion_ext.h"
#include "_plane.h"
#include "_plane2.h"
#include "_obb.h"
#include "_matrix.h"
#include "_matrix33.h"
#include "_fbox.h"
#include "_fbox2.h"
#include "_cylinder.h"
#include "_compressed_normal.h"
#include "_color.h"
#include "math_funcs.h"
#include "math_funcs_inline.h"
export module xr.Core.Math;