name: Release

on:
  push:
    branches:
      - cmake
  workflow_dispatch:

# Cancel previous run if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

env:
  packed-gamedata: 00_modded_exes_gamedata.db0

jobs:
  # Entrypoint
  anomaly:
    name: Anomaly
    runs-on: windows-latest
    environment: Anomaly.Release
    steps:
      - run: echo "Building Anomaly"

  # Compilation subcategory
  compile:
    name: Compile
    needs: anomaly
    runs-on: ubuntu-latest
    steps:
      - run: echo "Compiling..."

  # Compilation jobs
  binaries:
    name: Binaries
    needs: compile

    runs-on: windows-latest

    strategy:
      matrix:
        configure-preset:
         #- 'MSVS.MSVC.Ninja'
         #- 'MSVS.MSVC.Ninja.AVX'
          - 'System.Clang'
          - 'System.Clang.AVX'
         #- 'System.GNU'
         #- 'System.GNU.AVX'
        target:
          - 'Anomaly.DX8'
          - 'Anomaly.DX9'
          - 'Anomaly.DX10'
          - 'Anomaly.DX11'

    env:
      configure-preset: ${{matrix.configure-preset}}
      build-preset: 'RelWithDebInfo'
      target: ${{matrix.target}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env

    - name: Build Binary
      uses: ./.github/actions/cmake

    - name: Upload Binary
      uses: ./.github/actions/upload-binary

    - name: Upload PDB
      uses: ./.github/actions/upload-pdb

  # Packing subcategory
  pack:
    name: Pack
    needs: anomaly
    runs-on: ubuntu-latest
    steps:
      - run: echo "Packing..."

  # Packing jobs
  gamedata:
    name: Gamedata
    needs: pack
    runs-on: windows-latest

    env:
      configure-preset: 'System.Clang.AVX'
      build-preset: 'RelWithDebInfo'
      target: 'Gamedata'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env

    - name: Build Gamedata
      uses: ./.github/actions/build-gamedata

    - name: Upload Gamedata
      uses: ./.github/actions/upload-gamedata

  # Checking subcategory
  check:
    name: Check
    needs: anomaly
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking..."

  # Checking jobs
  check-mixed-tabs:
    name: Mixed Spaces & Tabs
    needs: check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./.github/actions/check-mixed-tabs

  check-trailing-whitespace:
    name: Trailing Whitespace
    needs: check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Trailing Whitespace
      uses: ./.github/actions/check-trailing-whitespace

  check-terminating-newline:
    name: Terminating Newline
    needs: check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Newline Endings
      uses: ./.github/actions/check-terminating-newline

  check-utf8:
    name: UTF-8 Encoding
    needs: check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: UTF-8
      uses: ./.github/actions/check-utf8

  check-line-endings:
    name: Line Endings
    needs: check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Line Endings
      uses: ./.github/actions/check-line-endings

  # Release job
  release:
    needs: [
      binaries,
      gamedata,
      check-mixed-tabs,
      check-trailing-whitespace,
      check-terminating-newline,
      check-line-endings,
      check-utf8
    ]
    name: Release
    runs-on: ubuntu-latest
    env:
      configure-preset: System.Clang
      build-preset: RelWithDebInfo
    steps:
    - uses: actions/checkout@v4

    - name: Get Datetime
      id: datetime
      run: echo "::set-output name=today::$(date +'%-Y.%-m.%-d')"

    # Use the output from the `datetime` step
    - name: Print Version
      env:
        VERSION: "${{steps.datetime.outputs.today}}"
      run: echo "VERSION ${{steps.datetime.outputs.today}}"

    - name: Download Artifacts
      uses: ./.github/actions/download-artifacts

    - name: Pack Binaries
      uses: ./.github/actions/pack-binaries
      with:
        name: STALKER-Anomaly-modded-exes_${{steps.datetime.outputs.today}}

    - name: Pack PDBs
      uses: ./.github/actions/pack-pdbs

    - name: Publish
      uses: ./.github/actions/publish-release
      with:
        name: ${{steps.datetime.outputs.today}}
        token: ${{secrets.GITHUB_TOKEN}}
